# -*- coding: utf-8 -*-
"""CS CM 124 Challenge 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vxHfQwemyEcDNtVX3ZIn9extOOwEVwj5
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso, LinearRegression
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score
import numpy as np
import pandas as pd
import os



# Load data
train_genotype = np.loadtxt('train.genotype.txt')
train_phenotype = np.loadtxt('train.phenotype.txt')
test_genotype = np.loadtxt('test.genotype.txt')

# Split data
X_train, X_val, y_train, y_val = train_test_split(train_genotype, train_phenotype, test_size=0.2, random_state=42)




lasso = Lasso(alpha=0.05, random_state=42)
lasso.fit(train_genotype, train_phenotype)

final_predictions = lasso.predict(test_genotype)





pd.DataFrame(final_predictions).to_csv(f"predictions.csv", sep=",", header=None, index=None)

# Zip the predictions.csv file into predictions.zip
os.system("zip -r predictions.zip predictions.csv")
